version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    container_name: gpt4free
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8083:8083'
      - '1337:1337'
      - '7900:7900'